FileDrop.Web/Models/FilesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FileDrop.Domains;

namespace FileDrop.Web.Models
{
    public class FilesViewModel
    {
        public List<File> Files { get; set; }
        public long UserId { get; set; }

        public FilesViewModel()
        {
            Files = new List<File>();
        }

        public FilesViewModel(List<File> files, long userId)
        {
            Files = files;
            UserId = userId;
        }
    }
}

FileDrop.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace FileDrop.Web.Models.Layout
{
    public class UserInfoViewModel
    {
        public bool IsLoggedIn { get; set; }

        public string UserName { get; set; }
    }
}

FileDrop.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace FileDrop.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }

        public bool IsLoggedIn { get; set; }
    }
}

FileDrop.Web/Controllers/FileController.cs
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Abp.Runtime.Session;
using Abp.UI;
using Abp.Web.Mvc.Authorization;
using FileDrop.Interfaces;
using FileDrop.Web.Helpers;
using FileDrop.Web.Models;
using File = FileDrop.Domains.File;

namespace FileDrop.Web.Controllers
{
    [AbpMvcAuthorize]
    public class FileController : FileDropControllerBase
    {
        #region Private Fields
        private readonly IFileService _fileService;
        #endregion

        #region Constructors

        public FileController(IFileService fileService)
        {
            _fileService = fileService;
        }

        #endregion

        #region Public Methods

        public PartialViewResult GetAllFiles(string searchTerm, bool filter)
        {
            var userId = AbpSession.GetUserId();
            var files = _fileService.GetAllFilesForUser(userId, searchTerm, filter);
            var model = new FilesViewModel {Files = files.ToList()};

            return PartialView("_FilesTable", model);
        }

        public ActionResult Index()
        {
            var userId = AbpSession.GetUserId();
            var files = _fileService.GetAllFilesForUser(userId, string.Empty, false).ToList();
            var model = new FilesViewModel(files, userId);

            ViewBag.IsLoggedIn = true;

            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateFileName(int id, string fileName)
        {
            var file = await _fileService.GetFileByIdAsync(id);
            file.FileName = fileName;

            await _fileService.SaveFileAsync(file);

            return Json(new {saved = true});
        }

        [HttpPost]
        public async Task<ActionResult> UploadFile()
        {
            string fileName = "";
            var userId = AbpSession.GetUserId();

            try
            {
                foreach (HttpPostedFileBase file in Request.Files.Cast<string>().Select(fileItem => Request.Files[fileItem]).Where(file => file != null))
                {
                    fileName = file.FileName;
                    var fileSize = file.ContentLength;

                    // check to make sure we actually have a file
                    if (file.ContentLength <= 0) throw new UserFriendlyException("I'm sorry, there was an error saving the file.");

                    // read in the file into a byte array
                    byte[] binaryFile;
                    using (var binaryReady = new BinaryReader(file.InputStream))
                    {
                        binaryFile = binaryReady.ReadBytes(file.ContentLength);
                    }

                    var fullPath = FileHelpers.GetPath(fileName, Server.MapPath(@"\App_Data\"), userId);
                    var saveFile = new File
                    {
                        FileName = fileName, // don't save the file name with the extension
                        FileSize = FileHelpers.BytesToMegaBytes(fileSize),
                        FileType = file.ContentType,
                        FilePath = fullPath,
                        UploadDateTime = DateTime.Now,
                        IsImage = FileHelpers.IsImage(file.ContentType),
                        UserId = userId
                    };

                    // go back to the main UI thread and do whatever until we are ready
                    await FileHelpers.EncryptFileToDiskAsync(binaryFile, fullPath, "zxcvbgfdsaqwert54321");
                    await _fileService.SaveFileAsync(saveFile);
                }
                
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return Json(new {message = fileName});

        }

        [HttpPost]
        public async Task<ActionResult> SaveEditedImage(ImageEditorViewModel imageEditorViewModel)
        {
            var userId = AbpSession.GetUserId();
            // continue on with whatever we need to do until we get this file and are ready to do something with it
            var fileTask = _fileService.GetFileByIdAsync(imageEditorViewModel.FileId);

            // make a regular expression to get the type and image data quickly
            var imageRegex = Regex.Match(imageEditorViewModel.DataUrl, @"data:image/(?<type>.+?),(?<data>.+)");
            var imageType = imageRegex.Groups["type"].Value.Split(';')[0];
            var base64Data = imageRegex.Groups["data"].Value;
            var binaryData = Convert.FromBase64String(base64Data);
            var size = binaryData.Length;
            string path;

            // we have done all the work we can do without requiring the file, no await till that task is done
            var file = await fileTask;
            // saving as a new file
            if (imageEditorViewModel.FileId == 0)
            {
                imageEditorViewModel.FileName += "." + imageType;
                path = FileHelpers.GetPath(imageEditorViewModel.FileName, Server.MapPath(@"\App_Data\"), userId);
            }
            else
            {
                path = file.FilePath;
            }

            await FileHelpers.EncryptFileToDiskAsync(binaryData, path, "zxcvbgfdsaqwert54321");

            // go ahead and return if we are not making a new file
            if (file.Id != 0) return Json(new {fileName = file.FileName});

            var newFile = new File
            {
                FileName = imageEditorViewModel.FileName,
                FilePath = path,
                FileSize = FileHelpers.BytesToMegaBytes(size),
                UploadDateTime = DateTime.Now,
                FileType = "image/" + imageType,
                IsImage = true,
                UserId = userId
            };

            await _fileService.SaveFileAsync(newFile);
            return Json(new {fileName = imageEditorViewModel.FileName});
        }

        public async Task<ActionResult> EditImage(int id)
        {
            var file = await _fileService.GetFileByIdAsync(id);
            var data = await FileHelpers.ReadAllBytesAsync(file.FilePath);
            var fileDecrypted = await FileHelpers.DecryptAsync(data, "zxcvbgfdsaqwert54321");
            var base64 = Convert.ToBase64String(fileDecrypted);
            var dataUrl = FileHelpers.ToDataUrl(base64, file.FileType);

            var model = new ImageEditorViewModel(file, dataUrl);
            return View("ImageEditor", model);
        }

        public async Task DownloadFile(int id)
        {
            var file = await _fileService.GetFileByIdAsync(id);
            var data = await FileHelpers.ReadAllBytesAsync(file.FilePath);
            var fileDecrypted = await FileHelpers.DecryptAsync(data, "zxcvbgfdsaqwert54321");

            Response.ContentType = MimeMapping.GetMimeMapping(file.FilePath);
            Response.AddHeader("Content-Disposition", string.Format("attachment; filename=" + Path.GetFileName(file.FilePath)));
            await Response.OutputStream.WriteAsync(fileDecrypted, 0, fileDecrypted.Length);
            Response.Flush();
        }

        public async Task DownloadArchive()
        {
            var userId = AbpSession.GetUserId();
            var files = _fileService.GetAllFilesForUser(userId, string.Empty, false);
            var tempDirectory = new DirectoryInfo(string.Format("{0}temp", Server.MapPath(@"\App_Data\")));
            var tempPath = Path.Combine(tempDirectory.ToString(), userId.ToString());
            var exists = Directory.Exists(tempPath);
            if (!exists)
            {
                Directory.CreateDirectory(tempPath);
            }

            // get all files ready to be archived
            foreach (var file in files)
            {
                var fullPath = string.Format("{0}\\{1}", tempPath, file.FileName);
                // decrypt the file and write the temp file
                var data = await FileHelpers.ReadAllBytesAsync(file.FilePath);
                var fileDecrypted = await FileHelpers.DecryptAsync(data, "zxcvbgfdsaqwert54321");
                System.IO.File.WriteAllBytes(fullPath, fileDecrypted);
            }

            // archive the files
            var archivePath = new DirectoryInfo(string.Format("{0}Archives", Server.MapPath(@"\App_Data\")));
            exists = Directory.Exists(archivePath.ToString());
            if (!exists)
            {
                Directory.CreateDirectory(archivePath.ToString());
            }
            var archive = Path.Combine(archivePath.ToString(), DateTime.Now.Ticks + ".zip");
            ZipFile.CreateFromDirectory(tempPath, archive, CompressionLevel.Fastest, true);

            var zipData = await FileHelpers.ReadAllBytesAsync(archive);
            Response.ContentType = MimeMapping.GetMimeMapping(archive);
            Response.AddHeader("Content-Disposition", string.Format("attachment; filename=" + Path.GetFileName(archive)));
            await Response.OutputStream.WriteAsync(zipData, 0, zipData.Length);
            Response.Flush();

            // Delete the temp directory and archive directory
            Directory.Delete(tempDirectory.ToString(), true);
            Directory.Delete(archivePath.ToString(), true);
        }

        #endregion
    }
}

FileDrop.Web/Controllers/LayoutController.cs
using System.Web;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Threading;
using FileDrop.Managers;
using FileDrop.Web.Models.Layout;
using Microsoft.Owin.Security;

namespace FileDrop.Web.Controllers
{
    public class LayoutController : FileDropControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILocalizationManager _localizationManager;
        private readonly UserManager _userManager;

        private IAuthenticationManager AuthenticationManager
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        public LayoutController(IUserNavigationManager userNavigationManager, ILocalizationManager localizationManager, UserManager userManager)
        {
            _userNavigationManager = userNavigationManager;
            _localizationManager = localizationManager;
            _userManager = userManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var isLoggedIn = AbpSession.UserId.HasValue;
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.UserId)),
                            ActiveMenuItemName = activeMenu,
                            IsLoggedIn = isLoggedIn
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult UserInfoBar()
        {
            var userId = AbpSession.UserId;
            string userName = string.Empty;

            if (userId.HasValue)
            {
                var user = AsyncHelper.RunSync(() =>_userManager.FindByIdAsync(userId.Value));
                userName = user.UserName;
            }

            var model = new UserInfoViewModel
                        {
                            UserName = userName,
                            IsLoggedIn = userId.HasValue,
                        };

            return PartialView("_UserInfoBar", model);
        }
    }
}

FileDrop.Web/Views/Shared/_BeforeAfterModal.cshtml
<!-- Modal -->
<div class="modal fade" id="beforeAfterModal" tabindex="-1" role="dialog" aria-labelledby="beforeAfterLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Before and After</h4>
            </div>
            <div class="modal-body">
                <label id="beforeAfterLabel">Before</label>
                <img src="" id="before" class="img-responsive" />
                <img src="" id="after" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <button id="beforeBtn" type="button" class="btn btn-default">Before</button>
                <button id="afterBtn" type="button" class="btn btn-default">After</button>
            </div>
        </div>
    </div>
</div>

FileDrop.Web/Views/Shared/_ColorEditor.cshtml
<div class="form-group">
    <label id="brightnessLabel" for="brightnessSlider">Brightness</label>
    <input id="brightnessSlider" type="range" min="-100" max="100" value="0" step="1" data-filter="brightness" />
</div>
<div class="form-group">
    <label id="contrastLabel" for="contrastSlider">Contrast</label>
    <input id="contrastSlider" type="range" min="-100" max="100" value="0" step="1" data-filter="contrast" />
</div>
<div class="form-group">
    <label id="hueLabel" for="hueSlider">Hue</label>
    <input id="hueSlider" type="range" min="0" max="300" value="0" step="1" data-filter="hue" />
</div>
<div class="form-group">
    <label id="vibranceLabel" for="vibranceSlider">Vibrance</label>
    <input id="vibranceSlider" type="range" min="0" max="400" value="0" step="1" data-filter="vibrance" />
</div>
<div class="form-group">
    <label id="sepiaLabel" for="sepiaSlider">Sepia</label>
    <input id="sepiaSlider" type="range" min="0" max="100" value="0" step="1" data-filter="sepia" />
</div>
<div class="form-group">
    <label id="gammaLabel" for="gammaSlider">Gamma</label>
    <input id="gammaSlider" type="range" min="1.0" max="5" value="1.0" step="0.1" data-filter="gamma" />
</div>
<div class="form-group">
    <label id="exposureLabel" for="exposureSlider">Exposure</label>
    <input id="exposureSlider" type="range" min="-100" max="100" value="0" step="1" data-filter="exposure" />
</div>

FileDrop.Web/Views/Shared/_FileUploadModal.cshtml
<!-- Modal -->
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="uploadModalLabel">Upload Files</h4>
            </div>
            <div class="modal-body" id="dropZoneDiv">
                <div class="form-group">
                    <div>
                        <div class="previewMessage">
                            <span>Click here to upload your files, or drag and drop a file into this box</span><br/>
                            <span>Your files will automatically be uploaded</span>
                        </div>
                    </div>
                </div>
                <div class="clearfix" id="progressSection" style="margin-top: 30px; display: none">
                    <div class="form-group" style="text-align: center">
                        @*<h4 style="color: white;">Progress</h4>*@
                        <div style="border: 1px solid white; width: 90%; height: 30px; margin-right: auto; margin-left: auto; border-radius: 25px; text-align: center;">
                            <div style="background-color: #2170c2; width: 0; height: 30px; border-radius: 25px 0 0 25px; " id="progressBar">
                            </div>
                            <span id="progressPercent" style="font-weight: bold; position: relative; top: -25px; z-index: 5000; color: black;">0%</span>
                        </div>
                    </div>
                    <div class="form-group" id="progressMessage" style="text-align: center">
                        <h4 style="color: white;">Uploading File, Please Wait...</h4>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

FileDrop.Web/Views/Shared/_FilesTable.cshtml
@model FileDrop.Web.Models.FilesViewModel

@if (Model.Files.Count <= 0)
{
    <div class="text-center text-muted">No Files Found...</div>
}

else
{
    <table class="table" id="filesTable" data-resourceurl="@Url.Action("GetAllFiles","File")">
        <thead>
            <tr>
                <th>File Name</th>
                <th>File Type</th>
                <th>File Size (MB)</th>
                <th>Uploaded On</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Files)
            {
                <tr>
                    <td data-fileid="@item.Id" data-filename="true" class="col-md-6">
                        <span class="editText">@item.FileName</span>
                        @Html.TextBoxFor(model => item.FileName, new {style = "display:none; width: 50%" })
                        <button data-url="@Url.Action("UpdateFileName", "File")" data-editmode="false" class="btn btn-danger btn-sm pull-right editFile" style="display: none">Rename</button>
                    </td>
                    <td>@item.FileType</td>
                    <td>@string.Format("{0:N2}", item.FileSize)</td>
                    <td>@item.UploadDateTime.ToShortDateString()</td>
                    <td>
                        <button data-fileid="@item.Id" data-resourceurl="@Url.Action("DownloadFile", "File", new {id = item.Id})" class="btn btn-sm btn-link downloadFile" data-toggle="tooltip" data-placement="top" title="Download File">
                            <i class="fa fa-download"></i>
                        </button>
                    </td>
                    <td>
                        @if (item.IsImage)
                        {
                            <button data-fileid="@item.Id" data-resourceurl="@Url.Action("EditImage", "File", new {id = item.Id})" class="btn btn-sm btn-link editImage" data-toggle="tooltip" data-placement="top" title="Edit Image">
                                <i class="fa fa-picture-o"></i>
                            </button>
                        }
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
        </tfoot>
    </table>
}

FileDrop.Web/Views/Shared/_FilterEditor.cshtml
    <label id="filtersLabel" for="filtersList">Filters</label>
<select class="form-control" id="filtersList">
    <option value="clarity">Clarity</option>
    <option value="crossProcess">Cross Process</option>
    <option value="greyscale">Greyscale</option>
    <option value="hdr">HDR</option>
    <option value="blur">Radial Blur</option>
    <option value="vintage">Vintage</option>
</select>

<button id="applyFilter" class="btn btn-primary">Apply Filter</button>

FileDrop.Web/Views/Shared/_ImageDetails.cshtml
@model FileDrop.Web.Models.ImageEditorViewModel

<span id="fileName"><strong>Filename: </strong> @Model.File.FileName</span> <br/>
<span id="imageWidth"><strong>Image Width: </strong></span> <br/>
<span id="imageHeight"><strong>Image Height: </strong></span> <br/>
<p></p>
@*<span><strong>Rotate Image:</strong> </span>
<i id="rotateLeft" class="fa fa-undo" style="cursor: pointer"></i>
<i id="rotateRight" class="fa fa-repeat" style="cursor: pointer"></i> <br/>*@

FileDrop.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>FileDrop</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1-rc.1/js/select2.min.js"></script>

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll"></script>
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

FileDrop.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/">FileDrop</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new {activeMenu = ViewBag.ActiveMenu})
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("UserInfoBar","Layout")
            </ul>
        </div>
    </div>
</div>